export const actions = {
    FIRST_ACTION: 'FIRST_ACTION',
    FETCH_DATA: 'FETCH_DATA',
    INIT_SUMMARY_DATA: 'INIT_SUMMARY_DATA',
    ADD_PAYEE: 'ADD_PAYEE',
    UPDATE_PAYEE: 'UPDATE_PAYEE',
    DELETE_PAYEE: 'DELETE_PAYEE',
    SET_GRAPH: 'SET_GRAPH'
}